### ISSUE TITLE
dt.img not found on cm12.1

### ISSUE THREAD

**Issue by kaneawk** [xadro/android_device_motorola_kinzie#4]
I'm tried to use cm12.1 to compile twrp, but failed. this is error log:

Target dt image: /data/android/cm/cm12.1/out/target/product/kinzie/dt.img
DTB combiner:
  Input directory: './'
  Output file: '/data/android/cm/cm12.1/out/target/product/kinzie/dt.img'
=> Found 0 unique DTB(s)
/data/android/cm/cm12.1/out/host/linux-x86/bin/checkpolicy:  loading policy configuration from /data/android/cm/cm12.1/out/target/product/kinzie/obj/ETC/sepolicy.recovery_intermediates/policy_recovery.conf
/data/android/cm/cm12.1/out/host/linux-x86/bin/checkpolicy:  policy configuration loaded
/data/android/cm/cm12.1/out/host/linux-x86/bin/checkpolicy:  writing binary representation (version 26) to /data/android/cm/cm12.1/out/target/product/kinzie/obj/ETC/sepolicy.recovery_intermediates/sepolicy.recovery
java -jar /data/android/cm/cm12.1/out/host/linux-x86/framework/dumpkey.jar build/target/product/security/testkey.x509.pem build/target/product/security/cm.x509.pem build/target/product/security/cm-devkey.x509.pem > /data/android/cm/cm12.1/out/target/product/kinzie/obj/PACKAGING/ota_keys_intermediates/keys
chmod: cannot access '/data/android/cm/cm12.1/out/target/product/kinzie/dt.img': No such file or directory
build/core/tasks/dt_image.mk:30: recipe for target '/data/android/cm/cm12.1/out/target/product/kinzie/dt.img' failed
make: **\* [/data/android/cm/cm12.1/out/target/product/kinzie/dt.img] Error 1
make: **\* Waiting for unfinished jobs....
/data/android/cm/cm12.1/out/host/linux-x86/bin/checkpolicy:  loading policy configuration from /data/android/cm/cm12.1/out/target/product/kinzie/obj/ETC/sepolicy_intermediates/policy.conf
/data/android/cm/cm12.1/out/host/linux-x86/bin/checkpolicy:  policy configuration loaded
/data/android/cm/cm12.1/out/host/linux-x86/bin/checkpolicy:  writing binary representation (version 26) to /data/android/cm/cm12.1/out/target/product/kinzie/obj/ETC/sepolicy_intermediates/sepolicy
/data/android/cm/cm12.1/out/host/linux-x86/bin/checkpolicy:  loading policy configuration from /data/android/cm/cm12.1/out/target/product/kinzie/obj/ETC/sepolicy_intermediates/policy.conf.dontaudit
/data/android/cm/cm12.1/out/host/linux-x86/bin/checkpolicy:  policy configuration loaded
/data/android/cm/cm12.1/out/host/linux-x86/bin/checkpolicy:  writing binary representation (version 26) to /data/android/cm/cm12.1/out/target/product/kinzie/obj/ETC/sepolicy_intermediates//sepolicy.dontaudit
[33mpreparing StaticLib:[0m libc_common_32 [including  /data/android/cm/cm12.1/out/target/product/kinzie/obj_arm/STATIC_LIBRARIES/libc_tzcode_intermediates/libc_tzcode.a]
[33mpreparing StaticLib:[0m libc_common_32 [including  /data/android/cm/cm12.1/out/target/product/kinzie/obj_arm/STATIC_LIBRARIES/libjemalloc_intermediates/libjemalloc.a]
[32mtarget StaticLib:[0m libc_common_32 (/data/android/cm/cm12.1/out/target/product/kinzie/obj_arm/STATIC_LIBRARIES/libc_common_intermediates/libc_common.a)
#### make failed to build some targets (07:28 (mm:ss))

I'm used the master branch.

**Comment by xadro** [comment]
Please don't use this tree for building twrp. It is very outdated. Use the twrp branch here: https://github.com/cm-kinzie-porting/device_motorola_kinzie/tree/cm-12.1-twrp
